### ISSUE TITLE
0.63.0 has dependancy error related to lazy_static

### ISSUE THREAD

**Issue by johnthagen** [PistonDevelopers/piston_window#184]
When I update my `Cargo.toml` from 

```toml
[dependencies]
piston_window = "0.62.0"
piston2d-opengl_graphics = "0.39.0"
piston-music = "0.18.0"
```

To:

```toml
[dependencies]
piston_window = "0.63.0"
piston2d-opengl_graphics = "0.39.0"
piston-music = "0.18.0"
```

I receive this error:

```bash
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `lazy_static` (required by `winit`):
all possible versions conflict with previously selected versions of `lazy_static`
  version 0.2.1 in use by lazy_static v0.2.1
  possible versions to select: 0.2.2
```

Trying to build on stable 1.14.0 MSVC x64. Not sure if this problem is upstream of `piston_window` or not.
